### PR TITLE
Fix/cascade

### LINKED ISSUE #465: [Bug]: prep remove does not work with mysql database
### Description

```text
Singularity will note remove a preparation using the `prep remove` command. Error indicates a sql issue
```

### Steps to Reproduce

1. run singularity with mysql as backend
2. start a prep
3. Run below commands
```
singularity prep remove --cars 1
```

### Version

singularity v0.5.14-f54c4c1

### Operating System

Linux

### Database Backend

MySQL

### Additional context

```
$ singularity prep remove --cars 5
2025-03-11T11:23:58.251-0400    INFO    database        database/connstring.go:45       Opening mysql database
2025-03-11T11:23:58.260-0400    ERROR   database        database/util.go:80     DELETE FROM `preparations` WHERE `preparations`.`id` = '8'      {"rowsAffected": 0, "elapsed": 0.002745421, "err": "Error 1296 (HY000): Got error 193 '`singularity`.`file_ranges`, CONSTRAINT `fk_files_file_ranges` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE' from InnoDB"}
Error 1296 (HY000): Got error 193 '`singularity`.`file_ranges`, CONSTRAINT `fk_files_file_ranges` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE' from InnoDB
```

This issue exists also when trying to run the delete command manually in mysql. This indicates some sort of mysql issues.

I managed to work around by first manually deleting file_ranges.

```
DELETE FROM file_ranges WHERE file_id IN (SELECT id FROM files WHERE attachment_id= 5);
```

Then performing the remove again.

`singularity prep remove --cars 5`

### PR DESCRIPTION
**Pull request by parkan**
fix postgres fk cascade deadlocks with set null + trigger approach
this addresses the postgres-specific foreign key constraint violations when deleting
preparations by implementing a database-level solution that:

1. makes files.attachment_id nullable
2. changes the fk constraint to ON DELETE SET NULL instead of restrict/no action
3. adds a postgres trigger that immediately deletes files when attachment_id becomes null

this approach keeps the application model unchanged (no pointer types) while solving
the constraint violation. the trigger ensures the app never sees null attachment_id
values so behavior stays consistent.

the solution is postgres-specific because:
- postgres has stricter fk enforcement that causes the deadlock/violation issues
- mysql tests were already passing with the existing restrict behavior
- we removed cascade deletes in https://github.com/data-preservation-programs/singularity/commit/640154ea7370989023d74a04d5692a8065f4e49a to avoid deadlocks, but that created
  the constraint violation when deleting preparations

longer term consideration: files conceptually belong to storages not preparations.
attachments are just prep<->storage associations. we might want to remove this fk
entirely since files should be storage-scoped and reusable across preparations
(expensive to re-scan). this would eliminate the cascade issues entirely while
enabling file reuse when recreating preparations with the same storage.

this resolves two issues that prevent deletion of preparations. fixes #465

### CODE REVIEW

**Comment by parkan** [comment]
this is waiting on validation (repro with test cherrypicked into parent branch + clear with my changes :crossed_fingers: ), if that works as intended it will be ready for review

File: cmd/admin/migrate.go [hunk 1]
```diff
@@ -101,7 +101,7 @@ var MigrateCmd = &cli.Command{
 				if err != nil {
 					return errors.WithStack(err)
 				}
-				fmt.Printf("Current migration: " + last + "\n")
+                fmt.Printf("Current migration: %s\n", last)
```
Comment (parkan) [inline cmd/admin/migrate.go:104]: test runner was complaining about this, I'm actually not 100% sure why but it seems happy now

Comment (parkan) [reply cmd/admin/migrate.go:104]: ok this seems to be a legit vet error :+1:

**Comment by parkan** [comment]
ok, test harness working locally in devcontainer, I've identified an issue with the FK pattern, will fix and push
